// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css";

const RootLayout = ({ children }) => {
  return (
    <html>
      <body>
        <h1 className="bg-black text-white p-[20px] text-center font-bold text-2xl">
          Header Section
        </h1>
        {children}
        <h1 className="bg-black text-white p-[20px] text-center font-bold text-2xl absolute bottom-0 w-full">
          Footer Section
        </h1>
      </body>
    </html>
  );
};

export default RootLayout;
